name: "Pichincha Ecu"
on:
  push:
    branches: [ develop ]
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  install:
    name: Install package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update pip3
        run: python3 -m pip install --upgrade pip
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install required packages
        run: |
            python3 -m pip install -r requirements.txt
            python -m pip install -r requirements.txt

  testing:
    name: Test code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: oryks code coverage action
        id: selftest
        uses: twyle/oryks-code-coverage@v0.1.0
        with:
          myinput: lyle

      - name: action output
        run: |
           echo "${{ steps.selftest.outputs.myoutput }}"

  build:
      name: Build and push image
      runs-on: ubuntu-latest
      needs: testing
      steps:
      - uses: actions/checkout@master
      - name: Check folders
        run: pwd
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



