name: "Pichincha Ecu"
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, main ]
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  install:
    name: Install package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update pip3
        run: python3 -m pip install --upgrade pip
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install required packages
        run: |
            python3 -m pip install -r requirements.txt
            python -m pip install -r requirements.txt
      - name: Coverage Badge
        run: |
          pwd
          mkdir -p coverage
          python -m coverage xml coverage.xml
          mv coverage.xml coverage/


  testing:
    name: Test code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Modify permission
        working-directory: coverage
        run: |
          chmod 777 coverage.xml
      - name: Get Cover
        if: github.event_name == 'pull_request'
        working-directory: coverage
        uses: orgoro/coverage@v3
        with:
            coverageFile: coverage/coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}

  build:
      name: Build and push image
      runs-on: ubuntu-latest
      needs: testing
      steps:
      - uses: actions/checkout@master
      - name: Check folders
        run: pwd
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



