name: "Pichincha Ecu"
on:
    push:
        branches: [develop]
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  install:
       name: Install package
       runs-on: ubuntu-latest

       steps:
       - name: Cdk install
         run: python -m pip install aws-cdk-lib
